### basic settings

# site properties and page defaults
title: Fallahi Bioinformatix Lab<sup>@2021-2024</sup>
description: Contains BioMed data analysis related materials
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: Fallahi-Bioinformatics-Lab/

# site social media and other links
links:
  email: fallahi.raziuni@gmail.com
  google-scholar: https://scholar.google.com.au/citations?user=Txj1NyEAAAAJ&hl=en
  github: https://github.com/Hossein-Fallahi
  twitter: Not Yet
  instagram: Not Yet
  youtube: Not Yet

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
   # markdown files in /_papers
  - scope:
      type: "Papers"
    values:
      layout: Papers
    # markdown files in /_projects
  - scope:
      type: "Projects"
    values:
      layout: Projects  

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
