   
- id: doi:10.1002/jcp.27386
  image: https://raw.githubusercontent.com/Hossein-Fallahi/Fallahi-Bioinformatics-Lab/main/images/Fig%204.jpg
  date: 2019-12-1
  extra-links:
    - type: website
      link: https://onlinelibrary.wiley.com/doi/epdf/10.1002/jcp.27386
    #- type: source
    # link: https://github.com/greenelab/meta-review
  tags:
    - Development, Netwrok analysis, TF Dynamics

- id: doi:10.1002/jcp.28520
  image: https://raw.githubusercontent.com/Hossein-Fallahi/Fallahi-Bioinformatics-Lab/main/images/falsafi.png
  #date: 2019-12-1
  extra-links:
    - type: website
      link: https://onlinelibrary.wiley.com/doi/abs/10.1002/jcp.28520
    #- type: source
    # link: https://github.com/greenelab/meta-review
  tags:
    - iPSCs, Netwrok analysis, RNA-seq, Direct Conversion
    
- id: doi:10.1111/jbg.12379
  image: https://raw.githubusercontent.com/Hossein-Fallahi/Fallahi-Bioinformatics-Lab/main/images/karami.png
  #date: 2019-12-1
  extra-links:
    - type: website
      link: https://onlinelibrary.wiley.com/doi/abs/10.1111/jbg.12379
    #- type: source
    # link: https://github.com/greenelab/meta-review
  tags:
    - Imprinting, Data minin, Machine learning, Random Forest
# id: doi:10.1371/journal.pcbi.1007128
# image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
# repo: greenelab/meta-review
# extra-links:
#   - type: manubot
#     link: https://greenelab.github.io/meta-review/
#   - type: source
#     link: https://github.com/greenelab/meta-review
#   - type: website
#     link: http://manubot.org/

# id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
#  repo: greenelab/meta-review
#  extra-links:
#   - type: preprint
#     link: https://doi.org/10.7287/peerj.preprints.3100v1
#   - type: manubot
#     link: https://greenelab.github.io/scihub-manuscript/
#   - type: source
#     link: https://github.com/greenelab/scihub-manuscript
#     text: Manuscript source
#   - type: source
#     link: https://github.com/greenelab/scihub
#     text: Analyses source
